server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KarthikPolampali/cloud-config
          search-paths:
          - 'station*'
          repos:
            perv:
              pattern: '*/perv'
              uri: https://github.com/KarthikPolampali/cloud-config-perv
              search-paths:
              - 'station*'