server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
  security:
    user:
      name: kp
      password: kp1
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/KarthikPolampali/cloud-config
          search-paths:
          - 'station*'
          repos:
            perv:
              pattern: '*/perv'
              uri: https://github.com/KarthikPolampali/cloud-config-perv
              search-paths:
              - 'station*'